apiVersion: apps/v1
kind: Deployment
metadata:
  name: hare-deployment
spec:
  selector:
    matchLabels:
      app: hare-and-bear
  replicas: 2
  template:
    metadata:
      labels:
        app: hare-and-bear
    spec:
      containers:
        - name: hare
          image: supergiantkir/animals:hare
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-deployment
spec:
  selector:
    matchLabels:
      app: hare-and-bear
  replicas: 1
  template:
    metadata:
      labels:
        app: hare-and-bear
    spec:
      containers:
        - name: bear
          image: supergiantkir/animals:bear
          ports:
            - containerPort: 80
---
kind: Service      # Create new service
apiVersion: v1
metadata:
  name: hare-and-bear-service # Name of the service (DNS - RFC 2929)
spec:
  selector:
    app: hare-and-bear    # Run on any pod with label - app:myapp
  ports:          # Map incoming port to target port
    - name: hare-and-bear-port    # Setting multiple ports listen
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
