apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hare-statefulset
spec:
  selector:
    matchLabels:
      app: hare
  replicas: 2
  template:
    metadata:
      labels:
        app: hare
    spec:
      containers:
        - name: hare
          image: supergiantkir/animals:hare
          ports:
            - containerPort: 80
  serviceName: "hare-service"
---
kind: Service      # Create new service
apiVersion: v1
metadata:
  name: hare-service # Name of the service (DNS - RFC 2929)
spec:
  selector:
    statefulset.kubernetes.io/pod-name: hare-statefulset    # Run on any pod with label - app:myapp
  ports:          # Map incoming port to target port
    - name: hare-port    # Setting multiple ports listen
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
