apiVersion: batch/v1
kind: Job
metadata:
  name: alpine
spec:
  template:
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: ["echo", "kfir"]
      restartPolicy: Never
  backoffLimit: 4

